package com.jmu.domain;

import java.io.Serializable;
import java.util.Date;

public class Auditing implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auditing.AUDITING_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String auditingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auditing.COMPANY_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auditing.AUDITING_STATE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private Short auditingState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auditing.FAIL_REASON
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String failReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auditing.CREATE_TIME
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auditing.AUDITING_TIME
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private Date auditingTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auditing.AUDITING_ID
     *
     * @return the value of auditing.AUDITING_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getAuditingId() {
        return auditingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auditing.AUDITING_ID
     *
     * @param auditingId the value for auditing.AUDITING_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setAuditingId(String auditingId) {
        this.auditingId = auditingId == null ? null : auditingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auditing.COMPANY_ID
     *
     * @return the value of auditing.COMPANY_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auditing.COMPANY_ID
     *
     * @param companyId the value for auditing.COMPANY_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auditing.AUDITING_STATE
     *
     * @return the value of auditing.AUDITING_STATE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public Short getAuditingState() {
        return auditingState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auditing.AUDITING_STATE
     *
     * @param auditingState the value for auditing.AUDITING_STATE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setAuditingState(Short auditingState) {
        this.auditingState = auditingState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auditing.FAIL_REASON
     *
     * @return the value of auditing.FAIL_REASON
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getFailReason() {
        return failReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auditing.FAIL_REASON
     *
     * @param failReason the value for auditing.FAIL_REASON
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setFailReason(String failReason) {
        this.failReason = failReason == null ? null : failReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auditing.CREATE_TIME
     *
     * @return the value of auditing.CREATE_TIME
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auditing.CREATE_TIME
     *
     * @param createTime the value for auditing.CREATE_TIME
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auditing.AUDITING_TIME
     *
     * @return the value of auditing.AUDITING_TIME
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public Date getAuditingTime() {
        return auditingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auditing.AUDITING_TIME
     *
     * @param auditingTime the value for auditing.AUDITING_TIME
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setAuditingTime(Date auditingTime) {
        this.auditingTime = auditingTime;
    }
}