package com.jmu.domain;

import java.io.Serializable;
import java.util.Date;

public class BullentinBoard implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bullentin_board.BULLENTIN_BOARD_ID
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    private String bullentinBoardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bullentin_board.COMPANY_ID
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bullentin_board.BULLENTIN_BOARD_TITLE
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    private String bullentinBoardTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bullentin_board.BB_ORDER
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    private Integer bbOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bullentin_board.CREATE_TIME
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bullentin_board.CREATOR
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bullentin_board.MODIFY_TIME
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bullentin_board.MODIFIER
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bullentin_board.STATUS
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bullentin_board.BULLENTIN_BOARD_CONTENT
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    private String bullentinBoardContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bullentin_board.BULLENTIN_BOARD_ID
     *
     * @return the value of bullentin_board.BULLENTIN_BOARD_ID
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public String getBullentinBoardId() {
        return bullentinBoardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bullentin_board.BULLENTIN_BOARD_ID
     *
     * @param bullentinBoardId the value for bullentin_board.BULLENTIN_BOARD_ID
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public void setBullentinBoardId(String bullentinBoardId) {
        this.bullentinBoardId = bullentinBoardId == null ? null : bullentinBoardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bullentin_board.COMPANY_ID
     *
     * @return the value of bullentin_board.COMPANY_ID
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bullentin_board.COMPANY_ID
     *
     * @param companyId the value for bullentin_board.COMPANY_ID
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bullentin_board.BULLENTIN_BOARD_TITLE
     *
     * @return the value of bullentin_board.BULLENTIN_BOARD_TITLE
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public String getBullentinBoardTitle() {
        return bullentinBoardTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bullentin_board.BULLENTIN_BOARD_TITLE
     *
     * @param bullentinBoardTitle the value for bullentin_board.BULLENTIN_BOARD_TITLE
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public void setBullentinBoardTitle(String bullentinBoardTitle) {
        this.bullentinBoardTitle = bullentinBoardTitle == null ? null : bullentinBoardTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bullentin_board.BB_ORDER
     *
     * @return the value of bullentin_board.BB_ORDER
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public Integer getBbOrder() {
        return bbOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bullentin_board.BB_ORDER
     *
     * @param bbOrder the value for bullentin_board.BB_ORDER
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public void setBbOrder(Integer bbOrder) {
        this.bbOrder = bbOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bullentin_board.CREATE_TIME
     *
     * @return the value of bullentin_board.CREATE_TIME
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bullentin_board.CREATE_TIME
     *
     * @param createTime the value for bullentin_board.CREATE_TIME
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bullentin_board.CREATOR
     *
     * @return the value of bullentin_board.CREATOR
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bullentin_board.CREATOR
     *
     * @param creator the value for bullentin_board.CREATOR
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bullentin_board.MODIFY_TIME
     *
     * @return the value of bullentin_board.MODIFY_TIME
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bullentin_board.MODIFY_TIME
     *
     * @param modifyTime the value for bullentin_board.MODIFY_TIME
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bullentin_board.MODIFIER
     *
     * @return the value of bullentin_board.MODIFIER
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bullentin_board.MODIFIER
     *
     * @param modifier the value for bullentin_board.MODIFIER
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bullentin_board.STATUS
     *
     * @return the value of bullentin_board.STATUS
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bullentin_board.STATUS
     *
     * @param status the value for bullentin_board.STATUS
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bullentin_board.BULLENTIN_BOARD_CONTENT
     *
     * @return the value of bullentin_board.BULLENTIN_BOARD_CONTENT
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public String getBullentinBoardContent() {
        return bullentinBoardContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bullentin_board.BULLENTIN_BOARD_CONTENT
     *
     * @param bullentinBoardContent the value for bullentin_board.BULLENTIN_BOARD_CONTENT
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public void setBullentinBoardContent(String bullentinBoardContent) {
        this.bullentinBoardContent = bullentinBoardContent == null ? null : bullentinBoardContent.trim();
    }
}