package com.jmu.domain;

import java.io.Serializable;
import java.util.Date;

public class Company implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.COMPANY_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.COMPANY_NAME
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.VISIT_URL
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String visitUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.SUBJECT_TYPE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private Short subjectType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.MAILBOX
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String mailbox;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.LOGO_SRC
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String logoSrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.COMPANY_STATE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private Short companyState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.ESTABLISHMENT_DATE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private Date establishmentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.INDUSTRY_TYPE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String industryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.REPRESENTATIVE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String representative;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.MOBILE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.TEL_PHONE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String telPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.ADDRESS
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.ZIP_CODE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String zipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.COMPANY_SIZE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private Short companySize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.CREATE_TIME
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.MODIFY_TIME
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.MODIFIER
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String modifier;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.COMPANY_ID
     *
     * @return the value of company.COMPANY_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.COMPANY_ID
     *
     * @param companyId the value for company.COMPANY_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.COMPANY_NAME
     *
     * @return the value of company.COMPANY_NAME
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.COMPANY_NAME
     *
     * @param companyName the value for company.COMPANY_NAME
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.VISIT_URL
     *
     * @return the value of company.VISIT_URL
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getVisitUrl() {
        return visitUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.VISIT_URL
     *
     * @param visitUrl the value for company.VISIT_URL
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setVisitUrl(String visitUrl) {
        this.visitUrl = visitUrl == null ? null : visitUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.SUBJECT_TYPE
     *
     * @return the value of company.SUBJECT_TYPE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public Short getSubjectType() {
        return subjectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.SUBJECT_TYPE
     *
     * @param subjectType the value for company.SUBJECT_TYPE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setSubjectType(Short subjectType) {
        this.subjectType = subjectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.MAILBOX
     *
     * @return the value of company.MAILBOX
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getMailbox() {
        return mailbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.MAILBOX
     *
     * @param mailbox the value for company.MAILBOX
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setMailbox(String mailbox) {
        this.mailbox = mailbox == null ? null : mailbox.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.LOGO_SRC
     *
     * @return the value of company.LOGO_SRC
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getLogoSrc() {
        return logoSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.LOGO_SRC
     *
     * @param logoSrc the value for company.LOGO_SRC
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setLogoSrc(String logoSrc) {
        this.logoSrc = logoSrc == null ? null : logoSrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.COMPANY_STATE
     *
     * @return the value of company.COMPANY_STATE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public Short getCompanyState() {
        return companyState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.COMPANY_STATE
     *
     * @param companyState the value for company.COMPANY_STATE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setCompanyState(Short companyState) {
        this.companyState = companyState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.ESTABLISHMENT_DATE
     *
     * @return the value of company.ESTABLISHMENT_DATE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public Date getEstablishmentDate() {
        return establishmentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.ESTABLISHMENT_DATE
     *
     * @param establishmentDate the value for company.ESTABLISHMENT_DATE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setEstablishmentDate(Date establishmentDate) {
        this.establishmentDate = establishmentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.INDUSTRY_TYPE
     *
     * @return the value of company.INDUSTRY_TYPE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getIndustryType() {
        return industryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.INDUSTRY_TYPE
     *
     * @param industryType the value for company.INDUSTRY_TYPE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setIndustryType(String industryType) {
        this.industryType = industryType == null ? null : industryType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.REPRESENTATIVE
     *
     * @return the value of company.REPRESENTATIVE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getRepresentative() {
        return representative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.REPRESENTATIVE
     *
     * @param representative the value for company.REPRESENTATIVE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setRepresentative(String representative) {
        this.representative = representative == null ? null : representative.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.MOBILE
     *
     * @return the value of company.MOBILE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.MOBILE
     *
     * @param mobile the value for company.MOBILE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.TEL_PHONE
     *
     * @return the value of company.TEL_PHONE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getTelPhone() {
        return telPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.TEL_PHONE
     *
     * @param telPhone the value for company.TEL_PHONE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setTelPhone(String telPhone) {
        this.telPhone = telPhone == null ? null : telPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.ADDRESS
     *
     * @return the value of company.ADDRESS
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.ADDRESS
     *
     * @param address the value for company.ADDRESS
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.ZIP_CODE
     *
     * @return the value of company.ZIP_CODE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.ZIP_CODE
     *
     * @param zipCode the value for company.ZIP_CODE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode == null ? null : zipCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.COMPANY_SIZE
     *
     * @return the value of company.COMPANY_SIZE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public Short getCompanySize() {
        return companySize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.COMPANY_SIZE
     *
     * @param companySize the value for company.COMPANY_SIZE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setCompanySize(Short companySize) {
        this.companySize = companySize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.CREATE_TIME
     *
     * @return the value of company.CREATE_TIME
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.CREATE_TIME
     *
     * @param createTime the value for company.CREATE_TIME
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.MODIFY_TIME
     *
     * @return the value of company.MODIFY_TIME
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.MODIFY_TIME
     *
     * @param modifyTime the value for company.MODIFY_TIME
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.MODIFIER
     *
     * @return the value of company.MODIFIER
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.MODIFIER
     *
     * @param modifier the value for company.MODIFIER
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }
}