package com.jmu.domain;

import java.io.Serializable;
import java.util.Date;

public class Product implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PRODUCT_ID
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.COMPANY_ID
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PRODUCT_IMG
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    private String productImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PRODUCT_DESC
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    private String productDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.STATE
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    private Short state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PRODUCT_ORDER
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    private Integer productOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.CREATE_TIME
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.CREATOR
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.MODIFY_TIME
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.MODIFIER
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    private String modifier;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PRODUCT_ID
     *
     * @return the value of product.PRODUCT_ID
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PRODUCT_ID
     *
     * @param productId the value for product.PRODUCT_ID
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.COMPANY_ID
     *
     * @return the value of product.COMPANY_ID
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.COMPANY_ID
     *
     * @param companyId the value for product.COMPANY_ID
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PRODUCT_IMG
     *
     * @return the value of product.PRODUCT_IMG
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public String getProductImg() {
        return productImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PRODUCT_IMG
     *
     * @param productImg the value for product.PRODUCT_IMG
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public void setProductImg(String productImg) {
        this.productImg = productImg == null ? null : productImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PRODUCT_DESC
     *
     * @return the value of product.PRODUCT_DESC
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PRODUCT_DESC
     *
     * @param productDesc the value for product.PRODUCT_DESC
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc == null ? null : productDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.STATE
     *
     * @return the value of product.STATE
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.STATE
     *
     * @param state the value for product.STATE
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public void setState(Short state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PRODUCT_ORDER
     *
     * @return the value of product.PRODUCT_ORDER
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public Integer getProductOrder() {
        return productOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PRODUCT_ORDER
     *
     * @param productOrder the value for product.PRODUCT_ORDER
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public void setProductOrder(Integer productOrder) {
        this.productOrder = productOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.CREATE_TIME
     *
     * @return the value of product.CREATE_TIME
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.CREATE_TIME
     *
     * @param createTime the value for product.CREATE_TIME
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.CREATOR
     *
     * @return the value of product.CREATOR
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.CREATOR
     *
     * @param creator the value for product.CREATOR
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.MODIFY_TIME
     *
     * @return the value of product.MODIFY_TIME
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.MODIFY_TIME
     *
     * @param modifyTime the value for product.MODIFY_TIME
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.MODIFIER
     *
     * @return the value of product.MODIFIER
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.MODIFIER
     *
     * @param modifier the value for product.MODIFIER
     *
     * @mbggenerated Wed May 17 17:42:15 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }
}