package com.jmu.domain;

import java.io.Serializable;

public class Rolefunction implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolefunction.ROLE_FUNC_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String roleFuncId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolefunction.ROLE_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolefunction.FUNCTION_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String functionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolefunction.ROLE_FUNC_ID
     *
     * @return the value of rolefunction.ROLE_FUNC_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getRoleFuncId() {
        return roleFuncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolefunction.ROLE_FUNC_ID
     *
     * @param roleFuncId the value for rolefunction.ROLE_FUNC_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setRoleFuncId(String roleFuncId) {
        this.roleFuncId = roleFuncId == null ? null : roleFuncId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolefunction.ROLE_ID
     *
     * @return the value of rolefunction.ROLE_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolefunction.ROLE_ID
     *
     * @param roleId the value for rolefunction.ROLE_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolefunction.FUNCTION_ID
     *
     * @return the value of rolefunction.FUNCTION_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolefunction.FUNCTION_ID
     *
     * @param functionId the value for rolefunction.FUNCTION_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setFunctionId(String functionId) {
        this.functionId = functionId == null ? null : functionId.trim();
    }
}