package com.jmu.domain;

import java.io.Serializable;

public class Sysfunction implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysfunction.FUNCTION_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String functionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysfunction.FUNCTION_NAME
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String functionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysfunction.FUNCTION_TYPE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private Short functionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysfunction.PARENT_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysfunction.ORDER_NO
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private Short orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysfunction.FUNCTION_URL
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String functionUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysfunction.FUNCTION_DESC
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String functionDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysfunction.FUNCTION_ID
     *
     * @return the value of sysfunction.FUNCTION_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysfunction.FUNCTION_ID
     *
     * @param functionId the value for sysfunction.FUNCTION_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setFunctionId(String functionId) {
        this.functionId = functionId == null ? null : functionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysfunction.FUNCTION_NAME
     *
     * @return the value of sysfunction.FUNCTION_NAME
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getFunctionName() {
        return functionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysfunction.FUNCTION_NAME
     *
     * @param functionName the value for sysfunction.FUNCTION_NAME
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setFunctionName(String functionName) {
        this.functionName = functionName == null ? null : functionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysfunction.FUNCTION_TYPE
     *
     * @return the value of sysfunction.FUNCTION_TYPE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public Short getFunctionType() {
        return functionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysfunction.FUNCTION_TYPE
     *
     * @param functionType the value for sysfunction.FUNCTION_TYPE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setFunctionType(Short functionType) {
        this.functionType = functionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysfunction.PARENT_ID
     *
     * @return the value of sysfunction.PARENT_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysfunction.PARENT_ID
     *
     * @param parentId the value for sysfunction.PARENT_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysfunction.ORDER_NO
     *
     * @return the value of sysfunction.ORDER_NO
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public Short getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysfunction.ORDER_NO
     *
     * @param orderNo the value for sysfunction.ORDER_NO
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setOrderNo(Short orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysfunction.FUNCTION_URL
     *
     * @return the value of sysfunction.FUNCTION_URL
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getFunctionUrl() {
        return functionUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysfunction.FUNCTION_URL
     *
     * @param functionUrl the value for sysfunction.FUNCTION_URL
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setFunctionUrl(String functionUrl) {
        this.functionUrl = functionUrl == null ? null : functionUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysfunction.FUNCTION_DESC
     *
     * @return the value of sysfunction.FUNCTION_DESC
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getFunctionDesc() {
        return functionDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysfunction.FUNCTION_DESC
     *
     * @param functionDesc the value for sysfunction.FUNCTION_DESC
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setFunctionDesc(String functionDesc) {
        this.functionDesc = functionDesc == null ? null : functionDesc.trim();
    }
}