package com.jmu.domain;

import java.io.Serializable;
import java.util.Date;

public class SysPicture implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_picture.PICTURE_ID
     *
     * @mbggenerated Thu May 04 21:24:06 CST 2017
     */
    private String pictureId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_picture.PICTURE_NAME
     *
     * @mbggenerated Thu May 04 21:24:06 CST 2017
     */
    private String pictureName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_picture.PICTURE_URL
     *
     * @mbggenerated Thu May 04 21:24:06 CST 2017
     */
    private String pictureUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_picture.PICTURE_TYPE
     *
     * @mbggenerated Thu May 04 21:24:06 CST 2017
     */
    private Short pictureType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_picture.COMPANY_ID
     *
     * @mbggenerated Thu May 04 21:24:06 CST 2017
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_picture.PICTURE_DESC
     *
     * @mbggenerated Thu May 04 21:24:06 CST 2017
     */
    private String pictureDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_picture.PICTURE_SORT
     *
     * @mbggenerated Thu May 04 21:24:06 CST 2017
     */
    private String pictureSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_picture.MODIFY_TIME
     *
     * @mbggenerated Thu May 04 21:24:06 CST 2017
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_picture.PICTURE_ID
     *
     * @return the value of sys_picture.PICTURE_ID
     *
     * @mbggenerated Thu May 04 21:24:06 CST 2017
     */
    public String getPictureId() {
        return pictureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_picture.PICTURE_ID
     *
     * @param pictureId the value for sys_picture.PICTURE_ID
     *
     * @mbggenerated Thu May 04 21:24:06 CST 2017
     */
    public void setPictureId(String pictureId) {
        this.pictureId = pictureId == null ? null : pictureId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_picture.PICTURE_NAME
     *
     * @return the value of sys_picture.PICTURE_NAME
     *
     * @mbggenerated Thu May 04 21:24:06 CST 2017
     */
    public String getPictureName() {
        return pictureName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_picture.PICTURE_NAME
     *
     * @param pictureName the value for sys_picture.PICTURE_NAME
     *
     * @mbggenerated Thu May 04 21:24:06 CST 2017
     */
    public void setPictureName(String pictureName) {
        this.pictureName = pictureName == null ? null : pictureName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_picture.PICTURE_URL
     *
     * @return the value of sys_picture.PICTURE_URL
     *
     * @mbggenerated Thu May 04 21:24:06 CST 2017
     */
    public String getPictureUrl() {
        return pictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_picture.PICTURE_URL
     *
     * @param pictureUrl the value for sys_picture.PICTURE_URL
     *
     * @mbggenerated Thu May 04 21:24:06 CST 2017
     */
    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl == null ? null : pictureUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_picture.PICTURE_TYPE
     *
     * @return the value of sys_picture.PICTURE_TYPE
     *
     * @mbggenerated Thu May 04 21:24:06 CST 2017
     */
    public Short getPictureType() {
        return pictureType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_picture.PICTURE_TYPE
     *
     * @param pictureType the value for sys_picture.PICTURE_TYPE
     *
     * @mbggenerated Thu May 04 21:24:06 CST 2017
     */
    public void setPictureType(Short pictureType) {
        this.pictureType = pictureType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_picture.COMPANY_ID
     *
     * @return the value of sys_picture.COMPANY_ID
     *
     * @mbggenerated Thu May 04 21:24:06 CST 2017
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_picture.COMPANY_ID
     *
     * @param companyId the value for sys_picture.COMPANY_ID
     *
     * @mbggenerated Thu May 04 21:24:06 CST 2017
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_picture.PICTURE_DESC
     *
     * @return the value of sys_picture.PICTURE_DESC
     *
     * @mbggenerated Thu May 04 21:24:06 CST 2017
     */
    public String getPictureDesc() {
        return pictureDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_picture.PICTURE_DESC
     *
     * @param pictureDesc the value for sys_picture.PICTURE_DESC
     *
     * @mbggenerated Thu May 04 21:24:06 CST 2017
     */
    public void setPictureDesc(String pictureDesc) {
        this.pictureDesc = pictureDesc == null ? null : pictureDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_picture.PICTURE_SORT
     *
     * @return the value of sys_picture.PICTURE_SORT
     *
     * @mbggenerated Thu May 04 21:24:06 CST 2017
     */
    public String getPictureSort() {
        return pictureSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_picture.PICTURE_SORT
     *
     * @param pictureSort the value for sys_picture.PICTURE_SORT
     *
     * @mbggenerated Thu May 04 21:24:06 CST 2017
     */
    public void setPictureSort(String pictureSort) {
        this.pictureSort = pictureSort == null ? null : pictureSort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_picture.MODIFY_TIME
     *
     * @return the value of sys_picture.MODIFY_TIME
     *
     * @mbggenerated Thu May 04 21:24:06 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_picture.MODIFY_TIME
     *
     * @param modifyTime the value for sys_picture.MODIFY_TIME
     *
     * @mbggenerated Thu May 04 21:24:06 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}