package com.jmu.domain;

import java.io.Serializable;
import java.util.Date;

public class Sysrole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysrole.ROLE_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysrole.ROLE_NAME
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysrole.ROLE_DESC
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String roleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysrole.COMPANY_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysrole.CREATE_TIME
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysrole.ROLE_ID
     *
     * @return the value of sysrole.ROLE_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysrole.ROLE_ID
     *
     * @param roleId the value for sysrole.ROLE_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysrole.ROLE_NAME
     *
     * @return the value of sysrole.ROLE_NAME
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysrole.ROLE_NAME
     *
     * @param roleName the value for sysrole.ROLE_NAME
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysrole.ROLE_DESC
     *
     * @return the value of sysrole.ROLE_DESC
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysrole.ROLE_DESC
     *
     * @param roleDesc the value for sysrole.ROLE_DESC
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc == null ? null : roleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysrole.COMPANY_ID
     *
     * @return the value of sysrole.COMPANY_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysrole.COMPANY_ID
     *
     * @param companyId the value for sysrole.COMPANY_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysrole.CREATE_TIME
     *
     * @return the value of sysrole.CREATE_TIME
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysrole.CREATE_TIME
     *
     * @param createTime the value for sysrole.CREATE_TIME
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}