package com.jmu.domain;

import java.io.Serializable;

public class Userrole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrole.USER_ROLE_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String userRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrole.USER_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrole.ROLE_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrole.USER_ROLE_ID
     *
     * @return the value of userrole.USER_ROLE_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getUserRoleId() {
        return userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrole.USER_ROLE_ID
     *
     * @param userRoleId the value for userrole.USER_ROLE_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setUserRoleId(String userRoleId) {
        this.userRoleId = userRoleId == null ? null : userRoleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrole.USER_ID
     *
     * @return the value of userrole.USER_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrole.USER_ID
     *
     * @param userId the value for userrole.USER_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrole.ROLE_ID
     *
     * @return the value of userrole.ROLE_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrole.ROLE_ID
     *
     * @param roleId the value for userrole.ROLE_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }
}