package com.jmu.domain;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.SYS_ACCOUNT
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String sysAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.MAILBOX
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String mailbox;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_NAME
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.PASSWORD
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.MOBILE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.SEX
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private Short sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.DUTIES
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String duties;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.BIRTHDAY
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ADDRESS
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.TEL_PHONE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String telPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ID_CARD
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.REMARK
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_TYPE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private Short userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.COMPANY_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.CREATE_TIME
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.PIC_SRC
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String picSrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.MODIFY_TIME
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.MODIFIER
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_STATE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private Short userState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.LCOK_REASON
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String lcokReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.STAFF_NO
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    private String staffNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_ID
     *
     * @return the value of user.USER_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_ID
     *
     * @param userId the value for user.USER_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.SYS_ACCOUNT
     *
     * @return the value of user.SYS_ACCOUNT
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getSysAccount() {
        return sysAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.SYS_ACCOUNT
     *
     * @param sysAccount the value for user.SYS_ACCOUNT
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setSysAccount(String sysAccount) {
        this.sysAccount = sysAccount == null ? null : sysAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.MAILBOX
     *
     * @return the value of user.MAILBOX
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getMailbox() {
        return mailbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.MAILBOX
     *
     * @param mailbox the value for user.MAILBOX
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setMailbox(String mailbox) {
        this.mailbox = mailbox == null ? null : mailbox.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_NAME
     *
     * @return the value of user.USER_NAME
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_NAME
     *
     * @param userName the value for user.USER_NAME
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.PASSWORD
     *
     * @return the value of user.PASSWORD
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.PASSWORD
     *
     * @param password the value for user.PASSWORD
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.MOBILE
     *
     * @return the value of user.MOBILE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.MOBILE
     *
     * @param mobile the value for user.MOBILE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.SEX
     *
     * @return the value of user.SEX
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public Short getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.SEX
     *
     * @param sex the value for user.SEX
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setSex(Short sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.DUTIES
     *
     * @return the value of user.DUTIES
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getDuties() {
        return duties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.DUTIES
     *
     * @param duties the value for user.DUTIES
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setDuties(String duties) {
        this.duties = duties == null ? null : duties.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.BIRTHDAY
     *
     * @return the value of user.BIRTHDAY
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.BIRTHDAY
     *
     * @param birthday the value for user.BIRTHDAY
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ADDRESS
     *
     * @return the value of user.ADDRESS
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ADDRESS
     *
     * @param address the value for user.ADDRESS
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.TEL_PHONE
     *
     * @return the value of user.TEL_PHONE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getTelPhone() {
        return telPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.TEL_PHONE
     *
     * @param telPhone the value for user.TEL_PHONE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setTelPhone(String telPhone) {
        this.telPhone = telPhone == null ? null : telPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ID_CARD
     *
     * @return the value of user.ID_CARD
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ID_CARD
     *
     * @param idCard the value for user.ID_CARD
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.REMARK
     *
     * @return the value of user.REMARK
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.REMARK
     *
     * @param remark the value for user.REMARK
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_TYPE
     *
     * @return the value of user.USER_TYPE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public Short getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_TYPE
     *
     * @param userType the value for user.USER_TYPE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setUserType(Short userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.COMPANY_ID
     *
     * @return the value of user.COMPANY_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.COMPANY_ID
     *
     * @param companyId the value for user.COMPANY_ID
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.CREATE_TIME
     *
     * @return the value of user.CREATE_TIME
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.CREATE_TIME
     *
     * @param createTime the value for user.CREATE_TIME
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.PIC_SRC
     *
     * @return the value of user.PIC_SRC
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getPicSrc() {
        return picSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.PIC_SRC
     *
     * @param picSrc the value for user.PIC_SRC
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setPicSrc(String picSrc) {
        this.picSrc = picSrc == null ? null : picSrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.MODIFY_TIME
     *
     * @return the value of user.MODIFY_TIME
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.MODIFY_TIME
     *
     * @param modifyTime the value for user.MODIFY_TIME
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.MODIFIER
     *
     * @return the value of user.MODIFIER
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.MODIFIER
     *
     * @param modifier the value for user.MODIFIER
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_STATE
     *
     * @return the value of user.USER_STATE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public Short getUserState() {
        return userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_STATE
     *
     * @param userState the value for user.USER_STATE
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setUserState(Short userState) {
        this.userState = userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.LCOK_REASON
     *
     * @return the value of user.LCOK_REASON
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getLcokReason() {
        return lcokReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.LCOK_REASON
     *
     * @param lcokReason the value for user.LCOK_REASON
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setLcokReason(String lcokReason) {
        this.lcokReason = lcokReason == null ? null : lcokReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.STAFF_NO
     *
     * @return the value of user.STAFF_NO
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public String getStaffNo() {
        return staffNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.STAFF_NO
     *
     * @param staffNo the value for user.STAFF_NO
     *
     * @mbggenerated Thu Apr 27 00:17:05 CST 2017
     */
    public void setStaffNo(String staffNo) {
        this.staffNo = staffNo == null ? null : staffNo.trim();
    }
}