package com.jmu.domain;

import java.io.Serializable;
import java.util.Date;

public class WebContent implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_content.CONTENT_ID
     *
     * @mbggenerated Sun May 07 01:25:04 CST 2017
     */
    private String contentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_content.COMPANY_ID
     *
     * @mbggenerated Sun May 07 01:25:04 CST 2017
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_content.COMUMN_ID
     *
     * @mbggenerated Sun May 07 01:25:04 CST 2017
     */
    private String comumnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_content.POSITION_X
     *
     * @mbggenerated Sun May 07 01:25:04 CST 2017
     */
    private Integer positionX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_content.POSITION_Y
     *
     * @mbggenerated Sun May 07 01:25:04 CST 2017
     */
    private Integer positionY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_content.SIZE_WIDTH
     *
     * @mbggenerated Sun May 07 01:25:04 CST 2017
     */
    private Integer sizeWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_content.SIZE_HEIGHT
     *
     * @mbggenerated Sun May 07 01:25:04 CST 2017
     */
    private Integer sizeHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_content.COMPONENT_ID
     *
     * @mbggenerated Sun May 07 01:25:04 CST 2017
     */
    private String componentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_content.MODIFY_TME
     *
     * @mbggenerated Sun May 07 01:25:04 CST 2017
     */
    private Date modifyTme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_content.MODIFIER
     *
     * @mbggenerated Sun May 07 01:25:04 CST 2017
     */
    private String modifier;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_content.CONTENT_ID
     *
     * @return the value of web_content.CONTENT_ID
     *
     * @mbggenerated Sun May 07 01:25:04 CST 2017
     */
    public String getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_content.CONTENT_ID
     *
     * @param contentId the value for web_content.CONTENT_ID
     *
     * @mbggenerated Sun May 07 01:25:04 CST 2017
     */
    public void setContentId(String contentId) {
        this.contentId = contentId == null ? null : contentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_content.COMPANY_ID
     *
     * @return the value of web_content.COMPANY_ID
     *
     * @mbggenerated Sun May 07 01:25:04 CST 2017
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_content.COMPANY_ID
     *
     * @param companyId the value for web_content.COMPANY_ID
     *
     * @mbggenerated Sun May 07 01:25:04 CST 2017
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_content.COMUMN_ID
     *
     * @return the value of web_content.COMUMN_ID
     *
     * @mbggenerated Sun May 07 01:25:04 CST 2017
     */
    public String getComumnId() {
        return comumnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_content.COMUMN_ID
     *
     * @param comumnId the value for web_content.COMUMN_ID
     *
     * @mbggenerated Sun May 07 01:25:04 CST 2017
     */
    public void setComumnId(String comumnId) {
        this.comumnId = comumnId == null ? null : comumnId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_content.POSITION_X
     *
     * @return the value of web_content.POSITION_X
     *
     * @mbggenerated Sun May 07 01:25:04 CST 2017
     */
    public Integer getPositionX() {
        return positionX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_content.POSITION_X
     *
     * @param positionX the value for web_content.POSITION_X
     *
     * @mbggenerated Sun May 07 01:25:04 CST 2017
     */
    public void setPositionX(Integer positionX) {
        this.positionX = positionX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_content.POSITION_Y
     *
     * @return the value of web_content.POSITION_Y
     *
     * @mbggenerated Sun May 07 01:25:04 CST 2017
     */
    public Integer getPositionY() {
        return positionY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_content.POSITION_Y
     *
     * @param positionY the value for web_content.POSITION_Y
     *
     * @mbggenerated Sun May 07 01:25:04 CST 2017
     */
    public void setPositionY(Integer positionY) {
        this.positionY = positionY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_content.SIZE_WIDTH
     *
     * @return the value of web_content.SIZE_WIDTH
     *
     * @mbggenerated Sun May 07 01:25:04 CST 2017
     */
    public Integer getSizeWidth() {
        return sizeWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_content.SIZE_WIDTH
     *
     * @param sizeWidth the value for web_content.SIZE_WIDTH
     *
     * @mbggenerated Sun May 07 01:25:04 CST 2017
     */
    public void setSizeWidth(Integer sizeWidth) {
        this.sizeWidth = sizeWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_content.SIZE_HEIGHT
     *
     * @return the value of web_content.SIZE_HEIGHT
     *
     * @mbggenerated Sun May 07 01:25:04 CST 2017
     */
    public Integer getSizeHeight() {
        return sizeHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_content.SIZE_HEIGHT
     *
     * @param sizeHeight the value for web_content.SIZE_HEIGHT
     *
     * @mbggenerated Sun May 07 01:25:04 CST 2017
     */
    public void setSizeHeight(Integer sizeHeight) {
        this.sizeHeight = sizeHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_content.COMPONENT_ID
     *
     * @return the value of web_content.COMPONENT_ID
     *
     * @mbggenerated Sun May 07 01:25:04 CST 2017
     */
    public String getComponentId() {
        return componentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_content.COMPONENT_ID
     *
     * @param componentId the value for web_content.COMPONENT_ID
     *
     * @mbggenerated Sun May 07 01:25:04 CST 2017
     */
    public void setComponentId(String componentId) {
        this.componentId = componentId == null ? null : componentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_content.MODIFY_TME
     *
     * @return the value of web_content.MODIFY_TME
     *
     * @mbggenerated Sun May 07 01:25:04 CST 2017
     */
    public Date getModifyTme() {
        return modifyTme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_content.MODIFY_TME
     *
     * @param modifyTme the value for web_content.MODIFY_TME
     *
     * @mbggenerated Sun May 07 01:25:04 CST 2017
     */
    public void setModifyTme(Date modifyTme) {
        this.modifyTme = modifyTme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_content.MODIFIER
     *
     * @return the value of web_content.MODIFIER
     *
     * @mbggenerated Sun May 07 01:25:04 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_content.MODIFIER
     *
     * @param modifier the value for web_content.MODIFIER
     *
     * @mbggenerated Sun May 07 01:25:04 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }
}