package com.jmu.domain;

import java.io.Serializable;
import java.util.Date;

public class WebColumn implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_column.COLUMN_ID
     *
     * @mbggenerated Fri May 05 23:42:26 CST 2017
     */
    private String columnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_column.COLUMN_NAME
     *
     * @mbggenerated Fri May 05 23:42:26 CST 2017
     */
    private String columnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_column.COLUMN_TYPE
     *
     * @mbggenerated Fri May 05 23:42:26 CST 2017
     */
    private Short columnType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_column.URL
     *
     * @mbggenerated Fri May 05 23:42:26 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_column.COMPANEY_ID
     *
     * @mbggenerated Fri May 05 23:42:26 CST 2017
     */
    private String companeyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_column.CREATOR
     *
     * @mbggenerated Fri May 05 23:42:26 CST 2017
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_column.MODIFY_TIME
     *
     * @mbggenerated Fri May 05 23:42:26 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_column.MODIFIER
     *
     * @mbggenerated Fri May 05 23:42:26 CST 2017
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_column.CREATE_TIME
     *
     * @mbggenerated Fri May 05 23:42:26 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_column.STATE
     *
     * @mbggenerated Fri May 05 23:42:26 CST 2017
     */
    private Short state;

    // 是否选为菜单栏
    private Boolean isMenu;
    // 是否选为底部链接
    private Boolean isFooterLink;

    public WebColumn() {
    }

    public WebColumn(String columnId, String columnName, Short columnType, String url, String companeyId, String creator, Short state) {
        this.columnId = columnId;
        this.columnName = columnName;
        this.columnType = columnType;
        this.url = url;
        this.companeyId = companeyId;
        this.creator = creator;
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_column.COLUMN_ID
     *
     * @return the value of web_column.COLUMN_ID
     *
     * @mbggenerated Fri May 05 23:42:26 CST 2017
     */



    public String getColumnId() {
        return columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_column.COLUMN_ID
     *
     * @param columnId the value for web_column.COLUMN_ID
     *
     * @mbggenerated Fri May 05 23:42:26 CST 2017
     */
    public void setColumnId(String columnId) {
        this.columnId = columnId == null ? null : columnId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_column.COLUMN_NAME
     *
     * @return the value of web_column.COLUMN_NAME
     *
     * @mbggenerated Fri May 05 23:42:26 CST 2017
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_column.COLUMN_NAME
     *
     * @param columnName the value for web_column.COLUMN_NAME
     *
     * @mbggenerated Fri May 05 23:42:26 CST 2017
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName == null ? null : columnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_column.COLUMN_TYPE
     *
     * @return the value of web_column.COLUMN_TYPE
     *
     * @mbggenerated Fri May 05 23:42:26 CST 2017
     */
    public Short getColumnType() {
        return columnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_column.COLUMN_TYPE
     *
     * @param columnType the value for web_column.COLUMN_TYPE
     *
     * @mbggenerated Fri May 05 23:42:26 CST 2017
     */
    public void setColumnType(Short columnType) {
        this.columnType = columnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_column.URL
     *
     * @return the value of web_column.URL
     *
     * @mbggenerated Fri May 05 23:42:26 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_column.URL
     *
     * @param url the value for web_column.URL
     *
     * @mbggenerated Fri May 05 23:42:26 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_column.COMPANEY_ID
     *
     * @return the value of web_column.COMPANEY_ID
     *
     * @mbggenerated Fri May 05 23:42:26 CST 2017
     */
    public String getCompaneyId() {
        return companeyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_column.COMPANEY_ID
     *
     * @param companeyId the value for web_column.COMPANEY_ID
     *
     * @mbggenerated Fri May 05 23:42:26 CST 2017
     */
    public void setCompaneyId(String companeyId) {
        this.companeyId = companeyId == null ? null : companeyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_column.CREATOR
     *
     * @return the value of web_column.CREATOR
     *
     * @mbggenerated Fri May 05 23:42:26 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_column.CREATOR
     *
     * @param creator the value for web_column.CREATOR
     *
     * @mbggenerated Fri May 05 23:42:26 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_column.MODIFY_TIME
     *
     * @return the value of web_column.MODIFY_TIME
     *
     * @mbggenerated Fri May 05 23:42:26 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_column.MODIFY_TIME
     *
     * @param modifyTime the value for web_column.MODIFY_TIME
     *
     * @mbggenerated Fri May 05 23:42:26 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_column.MODIFIER
     *
     * @return the value of web_column.MODIFIER
     *
     * @mbggenerated Fri May 05 23:42:26 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_column.MODIFIER
     *
     * @param modifier the value for web_column.MODIFIER
     *
     * @mbggenerated Fri May 05 23:42:26 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_column.CREATE_TIME
     *
     * @return the value of web_column.CREATE_TIME
     *
     * @mbggenerated Fri May 05 23:42:26 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_column.CREATE_TIME
     *
     * @param createTime the value for web_column.CREATE_TIME
     *
     * @mbggenerated Fri May 05 23:42:26 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_column.STATE
     *
     * @return the value of web_column.STATE
     *
     * @mbggenerated Fri May 05 23:42:26 CST 2017
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_column.STATE
     *
     * @param state the value for web_column.STATE
     *
     * @mbggenerated Fri May 05 23:42:26 CST 2017
     */
    public void setState(Short state) {
        this.state = state;
    }

    public Boolean getIsMenu() {
        return isMenu;
    }

    public void setIsMenu(Boolean menu) {
        isMenu = menu;
    }

    public Boolean getIsFooterLink() {
        return isFooterLink;
    }

    public void setIsFooterLink(Boolean footerLink) {
        isFooterLink = footerLink;
    }
}