package com.jmu.domain;

import java.io.Serializable;
import java.util.Date;

public class WebFooter implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_footer.FOOTER_ID
     *
     * @mbggenerated Sat May 06 01:40:34 CST 2017
     */
    private String footerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_footer.COMPANY_ID
     *
     * @mbggenerated Sat May 06 01:40:34 CST 2017
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_footer.Link_SELECT_IDS
     *
     * @mbggenerated Sat May 06 01:40:34 CST 2017
     */
    private String linkSelectIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_footer.MODIFY_TIME
     *
     * @mbggenerated Sat May 06 01:40:34 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_footer.MODIFIER
     *
     * @mbggenerated Sat May 06 01:40:34 CST 2017
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_footer.MENU_SELECT_IDS
     *
     * @mbggenerated Sat May 06 01:40:34 CST 2017
     */
    private String menuSelectIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_footer.COPYRIGHT_TEXT
     *
     * @mbggenerated Sat May 06 01:40:34 CST 2017
     */
    private String copyrightText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_footer.FOOTER_ID
     *
     * @return the value of web_footer.FOOTER_ID
     *
     * @mbggenerated Sat May 06 01:40:34 CST 2017
     */
    public String getFooterId() {
        return footerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_footer.FOOTER_ID
     *
     * @param footerId the value for web_footer.FOOTER_ID
     *
     * @mbggenerated Sat May 06 01:40:34 CST 2017
     */
    public void setFooterId(String footerId) {
        this.footerId = footerId == null ? null : footerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_footer.COMPANY_ID
     *
     * @return the value of web_footer.COMPANY_ID
     *
     * @mbggenerated Sat May 06 01:40:34 CST 2017
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_footer.COMPANY_ID
     *
     * @param companyId the value for web_footer.COMPANY_ID
     *
     * @mbggenerated Sat May 06 01:40:34 CST 2017
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_footer.Link_SELECT_IDS
     *
     * @return the value of web_footer.Link_SELECT_IDS
     *
     * @mbggenerated Sat May 06 01:40:34 CST 2017
     */
    public String getLinkSelectIds() {
        return linkSelectIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_footer.Link_SELECT_IDS
     *
     * @param linkSelectIds the value for web_footer.Link_SELECT_IDS
     *
     * @mbggenerated Sat May 06 01:40:34 CST 2017
     */
    public void setLinkSelectIds(String linkSelectIds) {
        this.linkSelectIds = linkSelectIds == null ? null : linkSelectIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_footer.MODIFY_TIME
     *
     * @return the value of web_footer.MODIFY_TIME
     *
     * @mbggenerated Sat May 06 01:40:34 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_footer.MODIFY_TIME
     *
     * @param modifyTime the value for web_footer.MODIFY_TIME
     *
     * @mbggenerated Sat May 06 01:40:34 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_footer.MODIFIER
     *
     * @return the value of web_footer.MODIFIER
     *
     * @mbggenerated Sat May 06 01:40:34 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_footer.MODIFIER
     *
     * @param modifier the value for web_footer.MODIFIER
     *
     * @mbggenerated Sat May 06 01:40:34 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_footer.MENU_SELECT_IDS
     *
     * @return the value of web_footer.MENU_SELECT_IDS
     *
     * @mbggenerated Sat May 06 01:40:34 CST 2017
     */
    public String getMenuSelectIds() {
        return menuSelectIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_footer.MENU_SELECT_IDS
     *
     * @param menuSelectIds the value for web_footer.MENU_SELECT_IDS
     *
     * @mbggenerated Sat May 06 01:40:34 CST 2017
     */
    public void setMenuSelectIds(String menuSelectIds) {
        this.menuSelectIds = menuSelectIds == null ? null : menuSelectIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_footer.COPYRIGHT_TEXT
     *
     * @return the value of web_footer.COPYRIGHT_TEXT
     *
     * @mbggenerated Sat May 06 01:40:34 CST 2017
     */
    public String getCopyrightText() {
        return copyrightText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_footer.COPYRIGHT_TEXT
     *
     * @param copyrightText the value for web_footer.COPYRIGHT_TEXT
     *
     * @mbggenerated Sat May 06 01:40:34 CST 2017
     */
    public void setCopyrightText(String copyrightText) {
        this.copyrightText = copyrightText == null ? null : copyrightText.trim();
    }
}