package com.jmu.domain;

import java.io.Serializable;
import java.util.Date;

public class WebHeader implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_header.HEADER_ID
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    private String headerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_header.COMPANY_ID
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_header.LOGO_PIC
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    private String logoPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_header.LOGO_POSITION_X
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    private Integer logoPositionX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_header.LOGO_POSITION_Y
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    private Integer logoPositionY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_header.LOGO_SIZE_WIDTH
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    private Integer logoSizeWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_header.LOGO_SIZE_HEIGHT
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    private Integer logoSizeHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_header.LOGO_RADIUS
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    private Integer logoRadius;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_header.LOGO_OPATICY
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    private Integer logoOpaticy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_header.TITLE_POSITION_X
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    private Integer titlePositionX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_header.TITLE_POSITION_Y
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    private Integer titlePositionY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_header.MODIFY_TIME
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_header.MODIFIER
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_header.TITLE_TEXT
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    private String titleText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_header.HEADER_ID
     *
     * @return the value of web_header.HEADER_ID
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    public String getHeaderId() {
        return headerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_header.HEADER_ID
     *
     * @param headerId the value for web_header.HEADER_ID
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    public void setHeaderId(String headerId) {
        this.headerId = headerId == null ? null : headerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_header.COMPANY_ID
     *
     * @return the value of web_header.COMPANY_ID
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_header.COMPANY_ID
     *
     * @param companyId the value for web_header.COMPANY_ID
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_header.LOGO_PIC
     *
     * @return the value of web_header.LOGO_PIC
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    public String getLogoPic() {
        return logoPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_header.LOGO_PIC
     *
     * @param logoPic the value for web_header.LOGO_PIC
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    public void setLogoPic(String logoPic) {
        this.logoPic = logoPic == null ? null : logoPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_header.LOGO_POSITION_X
     *
     * @return the value of web_header.LOGO_POSITION_X
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    public Integer getLogoPositionX() {
        return logoPositionX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_header.LOGO_POSITION_X
     *
     * @param logoPositionX the value for web_header.LOGO_POSITION_X
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    public void setLogoPositionX(Integer logoPositionX) {
        this.logoPositionX = logoPositionX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_header.LOGO_POSITION_Y
     *
     * @return the value of web_header.LOGO_POSITION_Y
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    public Integer getLogoPositionY() {
        return logoPositionY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_header.LOGO_POSITION_Y
     *
     * @param logoPositionY the value for web_header.LOGO_POSITION_Y
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    public void setLogoPositionY(Integer logoPositionY) {
        this.logoPositionY = logoPositionY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_header.LOGO_SIZE_WIDTH
     *
     * @return the value of web_header.LOGO_SIZE_WIDTH
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    public Integer getLogoSizeWidth() {
        return logoSizeWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_header.LOGO_SIZE_WIDTH
     *
     * @param logoSizeWidth the value for web_header.LOGO_SIZE_WIDTH
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    public void setLogoSizeWidth(Integer logoSizeWidth) {
        this.logoSizeWidth = logoSizeWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_header.LOGO_SIZE_HEIGHT
     *
     * @return the value of web_header.LOGO_SIZE_HEIGHT
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    public Integer getLogoSizeHeight() {
        return logoSizeHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_header.LOGO_SIZE_HEIGHT
     *
     * @param logoSizeHeight the value for web_header.LOGO_SIZE_HEIGHT
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    public void setLogoSizeHeight(Integer logoSizeHeight) {
        this.logoSizeHeight = logoSizeHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_header.LOGO_RADIUS
     *
     * @return the value of web_header.LOGO_RADIUS
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    public Integer getLogoRadius() {
        return logoRadius;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_header.LOGO_RADIUS
     *
     * @param logoRadius the value for web_header.LOGO_RADIUS
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    public void setLogoRadius(Integer logoRadius) {
        this.logoRadius = logoRadius;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_header.LOGO_OPATICY
     *
     * @return the value of web_header.LOGO_OPATICY
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    public Integer getLogoOpaticy() {
        return logoOpaticy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_header.LOGO_OPATICY
     *
     * @param logoOpaticy the value for web_header.LOGO_OPATICY
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    public void setLogoOpaticy(Integer logoOpaticy) {
        this.logoOpaticy = logoOpaticy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_header.TITLE_POSITION_X
     *
     * @return the value of web_header.TITLE_POSITION_X
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    public Integer getTitlePositionX() {
        return titlePositionX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_header.TITLE_POSITION_X
     *
     * @param titlePositionX the value for web_header.TITLE_POSITION_X
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    public void setTitlePositionX(Integer titlePositionX) {
        this.titlePositionX = titlePositionX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_header.TITLE_POSITION_Y
     *
     * @return the value of web_header.TITLE_POSITION_Y
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    public Integer getTitlePositionY() {
        return titlePositionY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_header.TITLE_POSITION_Y
     *
     * @param titlePositionY the value for web_header.TITLE_POSITION_Y
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    public void setTitlePositionY(Integer titlePositionY) {
        this.titlePositionY = titlePositionY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_header.MODIFY_TIME
     *
     * @return the value of web_header.MODIFY_TIME
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_header.MODIFY_TIME
     *
     * @param modifyTime the value for web_header.MODIFY_TIME
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_header.MODIFIER
     *
     * @return the value of web_header.MODIFIER
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_header.MODIFIER
     *
     * @param modifier the value for web_header.MODIFIER
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_header.TITLE_TEXT
     *
     * @return the value of web_header.TITLE_TEXT
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    public String getTitleText() {
        return titleText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_header.TITLE_TEXT
     *
     * @param titleText the value for web_header.TITLE_TEXT
     *
     * @mbggenerated Sat May 06 12:52:46 CST 2017
     */
    public void setTitleText(String titleText) {
        this.titleText = titleText == null ? null : titleText.trim();
    }
}